### ISSUE TITLE
Pixel Picker overflow bug

### ISSUE THREAD

**Issue by SampleProvider** [definitely-nobody-is-here/red-pixel-simulator#3]
The pixels in the pixel picker will overflow
![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/68207888/ac15424a-1752-4373-a9fb-c2f8b94fe596)

**Comment by spsquared** [comment]
This didn't need to be posted, but it's fixed now

**Comment by spsquared** [comment]
oops forgot to reference again #3
