### ISSUE TITLE
Pushers can push pistons

### ISSUE THREAD

**Issue by SampleProvider** [definitely-nobody-is-here/red-pixel-simulator#6]
![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/68207888/d6469435-2648-4677-b1a6-1efd2701c11d)
the pusher keeps moving right

**Comment by spsquared** [comment]
ok fixed

**Comment by spsquared** [comment]
Stop posting issues for tiny things like this; issues should only be made for problems that would require some real time for investigation, like the brush noise bug.
